[package]
name = "scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "*"
tokio = {version = "*", features = ["full"]}
regex = "*"
queues = "1.1.0"
serde_json = "*"